language: android

before_install:
 - chmod +x gradlew

android:
  components:
    - tools # Update preinstalled tools
    - platform-tools
    - build-tools-26.1.1
    - tools # Update tools again

    # The SDK version used to compile your project
    - android-26

